<?php

$medecins = [
    'Jean Dupont',
    'Sophie Moreau',
    'Marc Lefèvre',
    'Claire Bernard',
    'Antoine Girard',
    'Rosy Kani',
    'Élise Rousseau',
    'Nicolas Lambert',
    'Camille Dubois',
    'Thomas Petit',
    'Laura Robert',
    'Julien Richard',
    'Julie Durand',
    'Pierre Garcia',
    'Marie Martin',
    'Lucas Leroy',
    'Chloé Simon',
    'Alexandre Michel',
    'Emma Fournier',
    'Maxime Chevalier',
    'Léa François',
    'Hugo Lemoine',
    'Manon Roux',
    'Paul Garnier',
    'Sarah Moulin',
    'Benoît Rey',
    'Alice Denis',
    'Romain Blanc',
    'Lucie Guérin',
    'Olivier Morin',
    'Inès Gauthier',
    'Jérôme Perrin',
    'Margaux Robin',
    'Stéphane Clement',
    'Pauline Fabre',
    'David Barbier',
    'Amandine Arnaud',
    'Vincent Martel',
    'Céline Lacroix',
    'Mathieu Masson',
    'André Kani',
    'Océane Picard',
    'Guillaume Gérard',
    'Justine Leclerc',
    'Florian Hervé',
    'Eva Philippe',
    'Sébastien Bertrand',
    'Morgane Roche',
    'Adrien Boyer',
    'Salomé Schmitt',
    'Thibault Louis',
    'Laurie André',
];

$specialitesMedicales = [
    'Allergologie',
    'Anesthésiologie',
    'Andrologie',
    'Angéiologie',
    'Addictologie',
    'Anatomopathologie',
    'Audiologie',
    'Bactériologie',
    'Biochimie médicale',
    'Biologie médicale',
    'Cardiologie',
    'Chirurgie cardiaque',
    'Chirurgie digestive',
    'Chirurgie endocrinienne',
    'Chirurgie générale',
    'Chirurgie maxillo-faciale',
    'Chirurgie oncologique',
    'Chirurgie orthopédique',
    'Chirurgie pédiatrique',
    'Chirurgie plastique',
    'Chirurgie thoracique',
    'Chirurgie vasculaire',
    'Chirurgie viscérale',
    'Coloproctologie',
    'Cytologie',
    'Dermato-allergologie',
    'Dermatologie',
    'Diabétologie',
    'Échographie',
    'Embryologie',
    'Endocrinologie',
    'Épidémiologie',
    'Épithéliologie',
    'Gastro-entérologie',
    'Gériatrie',
    'Gynécologie médicale',
    'Gynécologie obstétrique',
    'Hématologie',
    'Hématologie biologique',
    'Hépatologie',
    'Histologie',
    'Immunologie',
    'Dentisterie',
    'Infectiologie',
    'Imagerie médicale',
    'Kinésithérapie',
    'Maladies infectieuses',
    'Mammologie',
    "Médecine d'urgence",
    'Médecine de la reproduction',
    'Médecine du sport',
    'Médecine du travail',
    'Médecine esthétique',
    'Médecine interne',
    'Médecine légale',
    'Médecine palliative',
    'Médecine physique',
    'Médecine préventive',
    'Médecine vasculaire',
    'Microbiologie',
    'Néonatologie',
    'Néphrologie',
    'Neurochirurgie',
    'Neurologie',
    'Neuroradiologie',
    'Nutrition',
    'Obstétrique',
    'Oncologie médicale',
    'Oncologie radiothérapie',
    'Ophtalmologie',
    'Orthodontie',
    'Orthophonie',
    'Orthopédie',
    'Oto-rhino-laryngologie (ORL)',
    'Parasitologie',
    'Pédiatrie',
    'Pneumologie',
    'Podologie',
    'Proctologie',
    'Psychiatrie',
    'Psychiatrie infanto-juvénile',
    'Psychologie clinique',
    'Radiologie',
    'Radiothérapie',
    'Réanimation médicale',
    'Rééducation fonctionnelle',
    'Rhumatologie',
    'Santé publique',
    'Sénologie',
    'Stomatologie',
    'Toxicologie',
    'Transplantation',
    'Traumatologie',
    'Urologie',
    'Virologie',
    'Acupuncture',
    'Homéopathie',
    'Mésothérapie',
    'Ostéopathie',
    'Phlébologie',
    'Sexologie',
];

$chansonsCelebres = [
    'Ne me quitte pas - Jacques Brel',
    'La Vie en rose - Édith Piaf',
    "L'Hymne à l'amour - Édith Piaf",
    'Milord - Édith Piaf',
    'Douce France - Charles Trenet',
    'La Mer - Charles Trenet',
    'Les Feuilles mortes - Yves Montand',
    "C'est si bon - Yves Montand",
    'Le Poinçonneur des Lilas - Serge Gainsbourg',
    "Je t'aime... moi non plus - Serge Gainsbourg & Jane Birkin",
    "Comme d'habitude - Claude François",
    'Alexandrie Alexandra - Claude François',
    'Mistral gagnant - Renaud',
    'Manhattan-Kaboul - Renaud & Axelle Red',
    'Les Corons - Pierre Bachelet',
    'En chantant - Michel Sardou',
    'Les Lacs du Connemara - Michel Sardou',
    "Je l'aime à mourir - Francis Cabrel",
    'Petite Marie - Francis Cabrel',
    "L'envie - Johnny Hallyday",
    'Allumer le feu - Johnny Hallyday',
    'Laura - Johnny Hallyday',
    'Sous le vent - Garou & Céline Dion',
    'Belle - Garou, Daniel Lavoie & Patrick Fiori',
    'Bohemian Rhapsody - Queen',
    'We Are the Champions - Queen',
    'Imagine - John Lennon',
    'Hey Jude - The Beatles',
    'Let It Be - The Beatles',
    'Yesterday - The Beatles',
    'Like a Rolling Stone - Bob Dylan',
    "Knockin' on Heaven's Door - Bob Dylan",
    'Stairway to Heaven - Led Zeppelin',
    'Hotel California - Eagles',
    "Sweet Child o' Mine - Guns N' Roses",
    "November Rain - Guns N' Roses",
    'Smells Like Teen Spirit - Nirvana',
    'Billie Jean - Michael Jackson',
    'Thriller - Michael Jackson',
    'Like a Virgin - Madonna',
    'Like a Prayer - Madonna',
    'I Will Always Love You - Whitney Houston',
    'My Heart Will Go On - Céline Dion',
    'Rolling in the Deep - Adele',
    'Someone Like You - Adele',
    'Hello - Adele',
    'Shape of You - Ed Sheeran',
    'Thinking Out Loud - Ed Sheeran',
    'Uptown Funk - Mark Ronson ft. Bruno Mars',
    'Satisfaction - The Rolling Stones',
    'Angie - The Rolling Stones',
    'Paint It Black - The Rolling Stones',
    'Whole Lotta Love - Led Zeppelin',
    'Back in Black - AC/DC',
    'Highway to Hell - AC/DC',
    'Thunderstruck - AC/DC',
    'Enter Sandman - Metallica',
    'Nothing Else Matters - Metallica',
    'One - Metallica',
    'Baby One More Time - Britney Spears',
    'Toxic - Britney Spears',
    'Oops!... I Did It Again - Britney Spears',
    'Viva La Vida - Coldplay',
    'Yellow - Coldplay',
    'The Scientist - Coldplay',
    'Clocks - Coldplay',
    'Fix You - Coldplay',
    'Hallelujah - Leonard Cohen',
    'Suzanne - Leonard Cohen',
    'Respect - Aretha Franklin',
    'I Say a Little Prayer - Aretha Franklin',
    "What's Going On - Marvin Gaye",
    'Sexual Healing - Marvin Gaye',
    'Superstition - Stevie Wonder',
    "Isn't She Lovely - Stevie Wonder",
    'Purple Rain - Prince',
    'When Doves Cry - Prince',
    'Lose Yourself - Eminem',
    'Stan - Eminem',
    'Happy - Pharrell Williams',
    'Get Lucky - Daft Punk ft. Pharrell Williams',
    'Blurred Lines - Robin Thicke',
    "Can't Stop the Feeling! - Justin Timberlake",
    'Shake It Off - Taylor Swift',
    'Blank Space - Taylor Swift',
    'Bad Romance - Lady Gaga',
    'Poker Face - Lady Gaga',
    'Firework - Katy Perry',
    'Roar - Katy Perry',
    'Wonderwall - Oasis',
    "Don't Look Back in Anger - Oasis",
    'Creep - Radiohead',
    'Karma Police - Radiohead',
    'With or Without You - U2',
    'One - U2',
    'Beautiful Day - U2',
    'Zombie - The Cranberries',
    'Linger - The Cranberries',
    'Dreams - The Cranberries',
];

$artistes = [
    'Jacques Brel',
    'Édith Piaf',
    'Charles Trenet',
    'Yves Montand',
    'Serge Gainsbourg',
    'Jane Birkin',
    'Claude François',
    'Renaud',
    'Axelle Red',
    'Pierre Bachelet',
    'Michel Sardou',
    'Francis Cabrel',
    'Johnny Hallyday',
    'Garou',
    'Céline Dion',
    'Garou',
    'Daniel Lavoie',
    'Patrick Fiori',
    'Queen',
    'Queen',
    'John Lennon',
    'The Beatles',
    'The Beatles',
    'The Beatles',
    'Bob Dylan',
    'Bob Dylan',
    'Led Zeppelin',
    'Eagles',
    'Guns N\' Roses',
    'Nirvana',
    'Michael Jackson',
    'Madonna',
    'Whitney Houston',
    'Céline Dion',
    'Adele',
    'Ed Sheeran',
    'Mark Ronson',
    'Bruno Mars',
    'The Rolling Stones',
    'Led Zeppelin',
    'AC/DC',
    'Metallica',
    'Britney Spears',
    'Coldplay',
    'Leonard Cohen',
    'Aretha Franklin',
    'Marvin Gaye',
    'Stevie Wonder',
    'Prince',
    'Eminem',
    'Pharrell Williams',
    'Daft Punk',
    'Robin Thicke',
    'Justin Timberlake',
    'Taylor Swift',
    'Lady Gaga',
    'Katy Perry',
    'Oasis',
    'Oasis',
    'Radiohead',
    'U2',
    'U2',
    'U2',
    'The Cranberries',
];
